ASO1901029/sk2020_5K

03.design/README.md

Figmaのリンクを貼ったので閲覧できるかの確認をお願いします

画面イメージに関する記述を追加

---

04.source/ideash/app/models/idea_log.rb
04.source/ideash/db/migrate/20200724010802_change_hash_link_from_ideas.rb
04.source/ideash/db/schema.rb
04.source/ideash/test/fixtures/idea_logs.yml
04.source/ideash/test/models/idea_log_test.rb

Na update schema

---

04.source/ideash/app/controllers/brainstorming_controller.rb
04.source/ideash/app/views/brainstorming/edit.html.erb
04.source/ideash/app/views/shared/_editmenu.html.erb

nk_brainstorm

---

04.source/ideash/app/assets/stylesheets/top.scss
04.source/ideash/app/views/top/index.html.erb
04.source/ideash/app/views/top/releasenote.html.erb
04.source/ideash/config/routes.rb

sa_create_homemenu

---

04.source/ideash/app/assets/stylesheets/brainstorming.scss
04.source/ideash/app/javascript/packs/idea/brainstorming_channel.js

sa_update_memo

---

04.source/ideash/app/javascript/packs/idea/brainstorming_channel.js

FIX JavaScriptを入力しても実行されないように修正

---

04.source/ideash/app/views/ideas/history.html.erb

FIX 履歴から遷移した際にブレインストーミングでEnterが反応しない問題(#52)に暫定的な修正を施した

---

04.source/ideash/app/views/shared/_memomenu.html.erb

Conflicts:
	04.source/ideash/app/views/shared/_memomenu.html.erb

FIX 画面右部のメモ一覧にブレインストーミングが表示されてしまう不具合を修正(#45)

---

04.source/ideash/app/assets/stylesheets/brainstorming.scss
04.source/ideash/app/assets/stylesheets/ideas.scss
04.source/ideash/app/assets/stylesheets/shared.scss
04.source/ideash/app/views/ideas/history.html.erb

issue #48 #49 #50 #51 　の修正を行いました

FIX 新規作成画面のバグ(仕様)#50を修正しました

---

04.source/ideash/app/assets/stylesheets/brainstorming.scss

#48_fix_bags

---

04.source/ideash/app/assets/stylesheets/brainstorming.scss
04.source/ideash/app/views/brainstorming/_process_1.html.erb

sa_fix_bags

---

04.source/ideash/app/controllers/application_controller.rb
04.source/ideash/app/controllers/brainstorming_controller.rb
04.source/ideash/app/controllers/memo_controller.rb

#61_nk_fix URLに別のcategoryを入力しても開けてしまう問題を修正

---

04.source/ideash/app/views/shared/_header.html.erb
04.source/ideash/config/routes.rb
04.source/ideash/spec/features/feature_spec.rb

#93 を改善後、featureテストで使用していたidea_pathをidea_home_pathに変更

#93_fix_km

---

04.source/ideash/app/views/ideas/category.html.erb
04.source/ideash/app/views/ideas/home.html.erb
04.source/ideash/app/views/mandarat/new.html.erb

#74 sa_create_mandarat_exprain

---

04.source/ideash/app/assets/stylesheets/mandarat.scss
04.source/ideash/app/views/mandarat/_shared.erb

#75 shared更新

---

04.source/ideash/app/javascript/packs/idea/brainstorming_channel.js

FIX #120,#121のスペースだけで投稿できる問題を修正

---

04.source/ideash/app/views/layouts/application.html.erb

ADD OPGの設定

---

04.source/ideash/Gemfile
04.source/ideash/Gemfile.lock
04.source/ideash/app/assets/stylesheets/application.css
04.source/ideash/app/assets/stylesheets/home.scss
04.source/ideash/app/assets/stylesheets/shared.scss
04.source/ideash/app/assets/stylesheets/top.scss
04.source/ideash/app/javascript/packs/application.js
04.source/ideash/app/javascript/packs/top.js
04.source/ideash/app/views/layouts/application.html.erb
04.source/ideash/app/views/top/index.html.erb
04.source/ideash/config/webpack/environment.js
04.source/ideash/package.json
04.source/ideash/yarn.lock

CDN経由ではなくYarnを使ってWebpacker経由で読み込むようにしました

#96 CSSやJSの読み込みにWebpackerを使うように

---

04.source/ideash/Gemfile
04.source/ideash/Gemfile.lock
04.source/ideash/app/views/brainstorming/new.html.erb
04.source/ideash/app/views/ideas/history.html.erb
04.source/ideash/app/views/ideas/home.html.erb
04.source/ideash/app/views/layouts/application.html.erb
04.source/ideash/app/views/shared/_editmenu.html.erb
04.source/ideash/app/views/shared/_header.html.erb
04.source/ideash/app/views/shared/_homemenu.html.erb
04.source/ideash/config/environments/development.rb
04.source/ideash/config/environments/production.rb
04.source/ideash/config/environments/test.rb

#123_kd_speed_up

---

04.source/ideash/app/views/ideas/account.html.erb
04.source/ideash/app/views/shared/_homemenu.html.erb

#146_km_fix

---

04.source/ideash/app/controllers/users/registrations_controller.rb
04.source/ideash/app/javascript/packs/user/account.js
04.source/ideash/app/views/ideas/account.html.erb

#118_fix_km

---

04.source/ideash/app/channels/idea_channel.rb

FIX #172のグループ名の変更に関するバグを修正

---

04.source/ideash/app/views/brainstorming/new.html.erb
04.source/ideash/app/views/ideas/history.html.erb
04.source/ideash/app/views/ideas/home.html.erb
04.source/ideash/app/views/layouts/application.html.erb
04.source/ideash/app/views/shared/_editmenu.html.erb
04.source/ideash/app/views/shared/_header.html.erb
04.source/ideash/app/views/shared/_homemenu.html.erb

主な原因はcacheが残っていることだったので残さないようにして対処
パフォーマンスが悪くなった場合、対応を考える

#171 productionモードで色々バグる問題を修正

---

04.source/ideash/app/javascript/packs/shared.js

ついでに処理の可読性を向上しました
!=nullとは若干意味合いが違うけどやりたい事的には問題ないかと。

FIX #161 画面サイズが小さいときにフェードインしない不具合を修正

---

04.source/ideash/app/views/brainstorming/new.html.erb
04.source/ideash/app/views/mandarat/new.html.erb
04.source/ideash/app/views/shared/_homemenu.html.erb

FIX #159, #181, #182

---

04.source/ideash/app/javascript/packs/shared/_editmenu.js
04.source/ideash/app/views/shared/_editmenu.html.erb

クリック時に画面外にコピー用のテキスト要素を生成
選択
クリップボードにコピー
要素を削除
の流れで実装しています。
なので何かを選択していた場合はそれが解除されます。

#152 _editmenuに招待ボタンを実装(クリックでURLをコピー)

---

04.source/ideash/app/assets/stylesheets/shared.scss
04.source/ideash/app/channels/idea_channel.rb
04.source/ideash/app/javascript/packs/idea/brainstorming_channel.js
04.source/ideash/app/models/idea_log.rb
04.source/ideash/app/views/brainstorming/new.html.erb
04.source/ideash/app/views/mandarat/new.html.erb
04.source/ideash/app/views/shared/_editmenu.html.erb

#193,195,198,199のissueを解決しています。

#193_195_198_199_na_fix

---

04.source/ideash/app/assets/stylesheets/mandarat.scss
04.source/ideash/app/views/mandarat/_process_1.html.erb
04.source/ideash/app/views/mandarat/_process_2.html.erb
04.source/ideash/app/views/mandarat/_shared.erb

#194 sa_update_mandarat_html_css

---

04.source/ideash/app/assets/stylesheets/brainstorming.scss
04.source/ideash/app/javascript/packs/idea/brainstorming_channel.js
04.source/ideash/app/views/brainstorming/_process_3.html.erb

#217 のブレインストーミングのグルーピング周りの表示を更新しています。

UPDATE #217 ブレインストーミングのグルーピング周りの表示を更新

---

04.source/ideash/app/channels/idea_channel.rb
04.source/ideash/app/controllers/mandarat_controller.rb
04.source/ideash/app/javascript/packs/idea/mandarat_channel.js
04.source/ideash/app/javascript/packs/user/account.js
04.source/ideash/app/views/mandarat/new.html.erb

マンダラートで無制限以外の時間の設定を行えるように更新しています。

#209 マンダラートで無制限以外の時間の設定を行えるように更新

---

04.source/ideash/app/views/brainstorming/new.html.erb

#251 ブレインストーミングの初期設定の時間を調整しました。

#251 ブレインストーミングの時間を調整

---

04.source/ideash/app/controllers/users/registrations_controller.rb
04.source/ideash/app/views/users/registrations/new.html.erb

#254 #255 のSignUp画面回りのバグを修正しています。

#254_#255_na_fix

---

04.source/ideash/app/views/users/registrations/new.html.erb

FIX SignUp画面のSignIn画面へのリンクの隣の英文がおかしいのを修正

---

04.source/ideash/app/assets/stylesheets/shared.scss
04.source/ideash/app/javascript/packs/application.js
04.source/ideash/app/javascript/packs/shared/_right_menu.js.erb
04.source/ideash/app/views/shared/_right_menu.html.erb
04.source/ideash/config/webpack/environment.js
04.source/ideash/config/webpacker.yml
04.source/ideash/package.json
04.source/ideash/yarn.lock
06.script/install.sh

#264 right_menuの手法名の頭にある？マークを押したら簡単な説明を表示したい

---

04.source/ideash/app/javascript/packs/application.js
04.source/ideash/app/javascript/packs/idea/word_slot.js
04.source/ideash/app/views/word_slot/edit.html.erb

#355 JSの読み込み方の修正
#356 スロット開始後の画面遷移すると大量にエラーが出る
#357 回すを連打するとバグる
上記に加えて単語スロットの処理を大幅に改修しました

単語スロットのバグ改善と処理を改修しました

---

04.source/ideash/app/javascript/packs/idea/word_slot.js

FIX #361 wordslotの処理を改善

---

04.source/ideash/app/channels/idea_channel.rb
04.source/ideash/app/javascript/packs/idea/brainstorming_channel.js
04.source/ideash/app/views/shared/_right_menu.html.erb

#169UPDATE 残り時間表示

---

04.source/ideash/app/assets/stylesheets/mandarat.scss
04.source/ideash/app/javascript/packs/idea/mandarat_channel.js
04.source/ideash/app/views/mandarat/_shared.erb

#241 マンダラートのミニマップの罫線が消える問題に対処

---

04.source/ideash/app/javascript/packs/common/new.js
04.source/ideash/app/views/brainstorming/new.html.erb
04.source/ideash/app/views/ideas/home.html.erb
04.source/ideash/app/views/mandarat/new.html.erb

#389
・ホーム画面のhow to use欄のLinkクラスを無効化（カーソルがクリック可能状態になっていた）
#390
・Fomantic-uiをマンダラートのNewに適用
・new.jsの無制限モード周りの処理を効率化
に対応。

#390 #389 マンダラートのnewにFomatnic-uiを適用

---

04.source/ideash/app/channels/idea_channel.rb
04.source/ideash/app/views/ideas/category.html.erb

#398 グループIDの割り振りがおかしい
#399 WordSlotのリンクの修正とWordガチャの誤字修正

#398_399_na_develop
